version: "3.7"

services:
  db:
    image: postgres:15-alpine
    container_name: db
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
        - djangonetwork
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresqlcls
    env_file:
      - .env
  web:
    build:
      context: .
    ports:
      - 8000:8000
    command: >
      sh -c "sleep 5 && \
             python manage.py migrate && \
             python manage.py collectstatic --no-input && \
             gunicorn --bind 0.0.0.0:8000 soil.wsgi:application"
    volumes:
      - /app:/soil/
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - djangonetwork
#  nginx:
#    build: ./nginx
#    restart: unless-stopped
#    volumes:
#      - static_volume:/home/app/web/staticfiles
#      - media_volume:/home/app/web/media
#      - /etc/letsencrypt:/etc/letsencrypt
#      - /var/www/certbot:/var/www/certbot
#    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
#    ports:
#      - 80:80
#      - 443:443
#    links:
#      - web:web
#    depends_on:
#      - web
#    networks:
#      - djangonetwork
networks:
    djangonetwork:
        driver: bridge

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
  static_volume:
    driver: local
  media_volume:
    driver: local