# Generated by Django 5.0.2 on 2025-03-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenology_app', '0002_tk_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='key',
            field=models.PositiveIntegerField(verbose_name='block'),
        ),
    ]
